package io.alw.css.cashflowconsumer.model.constants;

public interface ExceptionSubCategoryType {
    String INVALID_MESSAGE = "INVALID_MESSAGE";
    String INVALID_FO_VERSION = "INVALID_FO_VERSION";
    String INVALID_VALUE_DATE = "INVALID_VALUE_DATE";
    String INVALID_RATE = "INVALID_RATE";
    String INVALID_AMOUNT = "INVALID_AMOUNT";
    String INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE";
    String INVALID_TRADE_TYPE = "INVALID_TRADE_TYPE";
    String INVALID_TRADE_LEG_TYPE = "INVALID_TRADE_LEG_TYPE";
    String INVALID_TRADE_EVENT_TYPE = "INVALID_TRADE_EVENT_TYPE";
    String INVALID_TRADE_EVENT_ACTION = "INVALID_TRADE_EVENT_ACTION";
    String REVISION_TYPE_RESOLUTION_FAILURE = "REVISION_TYPE_RESOLUTION_FAILURE";
    String NOT_FIRST_VERSION = "NOT_FIRST_VERSION";
    String INVALID_SUBSEQUENT_VERSION_CF_CREATION_ATTEMPT = "INVALID_SUBSEQUENT_VERSION_CF_CREATION_ATTEMPT";
    
    String TRADE_ID_LEG_ID_MISMATCH = "TRADE_ID_LEG_ID_MISMATCH";
    String INCORRECT_CF_REVISION_TYPE = "INCORRECT_CF_REVISION_TYPE";
    String LAST_CASHFLOW_IS_CANCELLED = "LAST_CASHFLOW_IS_CANCELLED";

    String INACTIVE_OR_MISSING_SSI = "INACTIVE_OR_MISSING_SSI";
    String INACTIVE_COUNTERPARTY_CODE = "INACTIVE_COUNTERPARTY_CODE";
    String UNEXPECTED_REFDATA = "UNEXPECTED_REFDATA";
    String INACTIVE_OR_MISSING_NOSTRO = "INACTIVE_OR_MISSING_NOSTRO";
    String INACTIVE_ENTITY = "INACTIVE_ENTITY";
    String INACTIVE_CURRENCY = "INACTIVE_CURRENCY";

    String CASHFLOW_PERSISTENCE_FAILURE = "CASHFLOW_PERSISTENCE_FAILURE";
}
