{
  "type": "record",
  "name": "TradeLegAvro",
  "namespace": "io.alw.css.serialization.trade",
  "fields": [
    {
      "name": "amount",
      "type": {
        "type": "string",
        "java-class": "java.math.BigDecimal"
      }
    },
    {
      "name": "bookCode",
      "type": ["null","string"]
    },
    {
      "name": "counterBookCode",
      "type": ["null","string"]
    },
    {
      "name": "counterpartyCode",
      "type": "string"
    },
    {
      "name": "currCode",
      "type": "string"
    },
    {
      "name": "entityCode",
      "type": "string"
    },
    {
      "name": "payOrReceive",
      "type": {
        "type": "enum",
        "name": "PayOrReceive",
        "namespace": "io.alw.css.serialization.common",
        "symbols": [
          "PAY",
          "RECEIVE"
        ]
      }
    },
    {
      "name": "rate",
      "type": {
        "type": "string",
        "java-class": "java.math.BigDecimal"
      }
    },
    {
      "name": "tradeEventAction",
      "type": {
        "type": "enum",
        "name": "TradeEventAction",
        "namespace": "io.alw.css.serialization.common",
        "symbols": [
          "ADD",
          "MODIFY",
          "REMOVE"
        ]
      }
    },
    {
      "name": "tradeEventType",
      "type": {
        "type": "enum",
        "name": "TradeEventType",
        "namespace": "io.alw.css.serialization.common",
        "symbols": [
          "NEW_TRADE",
          "REBOOK",
          "AMEND",
          "CORRECTION",
          "BOOK_MOVE",
          "CANCEL",
          "EXERCISE",
          "KNOCK_OUT",
          "EXPIRE",
          "INTEREST_ACTION",
          "ROLL",
          "TERMINATE",
          "FIX",
          "UN_FIX",
          "COUPON",
          "MATURE"
        ]
      }
    },
    {
      "name": "tradeLegId",
      "type": "long"
    },
    {
      "name": "tradeLegType",
      "type": {
        "type": "enum",
        "name": "TradeLegType",
        "symbols": [
          "FX_SIDE1",
          "FX_SIDE2",
          "MM_PRINCIPAL",
          "MM_MATURITY",
          "MM_INTEREST",
          "PARENT_TRADE",
          "CHILD_TRADE"
        ]
      }
    },
    {
      "name": "tradeLegVersion",
      "type": "int"
    },
    {
      "name": "valueDate",
      "type": {
        "type": "int",
        "logicalType":"date"
      }
    }
  ]
}
