###------------ Spring
spring.config.activate.on-profile=local
###------------ Web Server
server.port=8082
server.ssl.enabled=false
#server.ssl.client-auth=need
logging.level.org.springframework=info
logging.level.org.springframework.web=info
logging.group.tomcat=org.apache.catalina,org.apache.coyote,org.apache.tomcat
logging.level.tomcat=info
###------------ Cache Config
ignite.hosts=127.0.0.1:10800
###------------ Kafka Topics
app.kafka.topic.trade-cash-generation-event=local.v1.css.trade-publisher.trade-cash-generation-event
app.kafka.topic.confirmation-match-request=local.v1.css.trade-publisher.confirmation-match-request
app.kafka.topic.confirmation-match-event=local.v1.css.trade-publisher.confirmation-match-event
###------------ Kafka Config
# Producer properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.security.protocol=PLAINTEXT
spring.kafka.properties.auto.register.schemas=true
spring.kafka.producer.properties.schema.registry.url=http://localhost:8995
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.enable.idempotence=true
spring.kafka.producer.retries=1
# Consumer properties: tradecash
kafka.consumer.tradecash.properties.schema.registry.url=http://localhost:8995
kafka.consumer.tradecash.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
kafka.consumer.tradecash.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
kafka.consumer.tradecash.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.tradecash.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
kafka.consumer.tradecash.properties.specific.avro.reader=true
kafka.consumer.tradecash.group-id=css_tradeconsumer
kafka.consumer.tradecash.auto-offset-reset=earliest
kafka.consumer.tradecash.enable-auto-commit=true
# Consumer properties: confmatch
kafka.consumer.confmatch.properties.schema.registry.url=http://localhost:8995
kafka.consumer.confmatch.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
kafka.consumer.confmatch.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
kafka.consumer.confmatch.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.confmatch.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
kafka.consumer.confmatch.properties.specific.avro.reader=true
kafka.consumer.confmatch.group-id=css_tradeconsumer
kafka.consumer.confmatch.auto-offset-reset=earliest
kafka.consumer.confmatch.enable-auto-commit=true
#default for spring now is, auto-commit is false and Ack-mode is batch
###------------ TradeConsumer(cfc) properties
app.cfc.suppress.upto-amount={USD:'1.0', EUR:'1.0', GBP:'1.0', CNH:'3.0', INR:'10.0'}
app.cfc.suppress.interbook-tx=true
rest.services.trade-generator=http://localhost:8081/trade/generators
trade-generator.start-switch=true