###------------ Spring Profile
spring.config.activate.on-profile=local
###------------ Server
server.port=8081
server.ssl.enabled=false
#server.ssl.client-auth=need
logging.level.org.springframework.web=info
logging.group.tomcat=org.apache.catalina,org.apache.coyote,org.apache.tomcat
logging.level.tomcat=info
###------------ Cache Config
ignite.hosts=127.0.0.1:10800
###------------ Kafka Topics
app.kafka.topic.trade-output=local.v1.css.trade-publisher-trade-output
app.kafka.topic.trade-match-request=local.v1.css.trade-match-request
###------------ Kafka Config
spring.kafka.properties.security.protocol=PLAINTEXT
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.properties.schema.registry.url=http://localhost:8995
spring.kafka.properties.auto.register.schemas=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.enable.idempotence=true
spring.kafka.producer.retries=1
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8995
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.consumer.group-id=css_tradeconsumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
#default for spring now is, auto-commit is false and Ack-mode is batch
#spring.kafka.producer.properties.retry.backoff.ms=250
###------------ Trade Publisher properties
###------------ Trade Template properties
trade.template.vd-forward-days=50
trade.template.vd-backward-days=25
trade.template.cfs-for-backvd-cf=50
trade.template.max-amendments=10
###------------ Trade Generator properties
trade.generator.frequency-seconds-default=120
trade.generator.frequency-seconds.-FX=15
trade.generator.frequency-seconds.-MM_TERM=30
trade.generator.frequency-seconds.-MM_CALL=60
trade.generator.frequency-seconds.-PAYMENT=180
trade.generator.frequency-seconds.-BOND=60
trade.generator.frequency-seconds.INTER_BOOK-=420
trade.generator.frequency-seconds.INTER_BRANCH-=320
trade.generator.frequency-seconds.INTER_COMPANY-=280
trade.generator.frequency-seconds.CORPORATE_ACTION-=500
